---
- name: Create folder on remote server
  file:
    path: "{{ prometheus_config_path }}"
    state: directory
    mode: 0755

- name: Template file on remote server
  template:
    src: prometheus-custom-values.yaml.j2
    dest: "{{ prometheus_config_path }}/prometheus-custom-values.yaml"
    mode: 0644
