---
- name: Install Helm Diff
  kubernetes.core.helm_plugin:
    state: present
    plugin_path: https://github.com/databus23/helm-diff

# https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#upgrading-an-existing-release-to-a-new-major-version
# - name: Download Custom Resource Definition
#   get_url:
#     url: "{{ prometheus_crds_url }}/{{ item }}"
#     dest: "{{ prometheus_crds_path }}"
#   loop: "{{ prometheus_crds_files }}"

# - name: Deploy Prometheus CRDs
#   community.kubernetes.k8s:
#     state: present
#     src: "{{ prometheus_crds_path }}/{{ item }}"
#   loop: "{{ prometheus_crds_files }}"

# - name: wait Prometheus CRDS install in Kubernetes cluster
#   pause:
#     seconds: 30

- name: Add prometheus-community chart repo
  community.kubernetes.helm_repository:
    name: prometheus
    repo_url: "{{ prometheus_charts_repo }}"

- name: Deploy prometheus with helm
  community.kubernetes.helm:
    name: prometheus
    chart_ref: prometheus/kube-prometheus-stack
    chart_version: "{{ prometheus_version }}"
    release_namespace: "{{ namespace }}"
    update_repo_cache: yes
    create_namespace: yes
    wait_timeout: "200"
    values_files:
      - "{{ prometheus_config_path }}/prometheus-custom-values.yaml"
