---
- name: Add prometheus-community chart repo
  kubernetes.core.helm_repository:
    name: prometheus
    repo_url: "{{ prometheus_charts_repo }}"

- name: Deploy prometheus with helm
  kubernetes.core.helm:
    name: prometheus
    chart_ref: prometheus/kube-prometheus-stack
    chart_version: "{{ prometheus_charts_version }}"
    release_namespace: "{{ namespace }}"
    update_repo_cache: yes
    create_namespace: yes
    wait_timeout: "200"
    values_files:
      - "{{ prometheus_config_path }}/prometheus-custom-values.yaml"
