---
- name: Template Fluentbit daemon set
  template:
    src: fluent-bit-ds.yaml.j2
    dest: "{{ fluent_manifests_path }}/fluent-bit-ds.yaml"
    mode: 0644

- name: Template Fluentbit service monitor
  template:
    src: fluent-bit-service-monitor.yaml.j2
    dest: "{{ fluent_manifests_path }}/fluent-bit-service-monitor.yaml"
    mode: 0644
  when: fluent_activate_metrics
