---
- name: Create folder on remote server
  file:
    path: "{{ fluent_manifests_path }}"
    state: directory
    mode: 0755


- name: Copy manifests
  copy:
    src: "{{ item }}"
    dest: "{{ fluent_manifests_path }}/{{ item }}"
  loop: "{{ fluent_manifests_files }}"
