---
- name: Create Namespace
  k8s:
    name: "{{ default_kubernetes_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Deploy Fluentbit
  k8s:
    state: present
    src: "{{ fluent_manifests_path }}/{{ item }}"
    namespace: "{{ default_kubernetes_namespace }}"
  loop: "{{ fluent_manifests_files + [ 'fluent-bit-ds.yaml' ] }}"

- name: Deploy service monitor for Fluentbit
  k8s:
    state: present
    src: "{{ fluent_manifests_path }}/fluent-bit-service-monitor.yaml"
  when: fluent_activate_metrics | bool
