---
- name: Create directory on remote server
  file:
    path: "{{ helm_charts_custom_config_path }}"
    state: directory
    mode: 0755

- name: Copy helm charts custom values
  copy:
    src: "{{ local_helm_charts_values_directory }}/{{ item }}"
    dest: "{{ helm_charts_custom_config_path }}/{{ item }}"
    mode: 0644
  loop:
    - scalardl-custom-values.yaml
    - schema-loading-custom-values.yaml
