---
- name: Deploy Scalar DL
  command: >-
    {{ helm_binary_path }} upgrade --install {{ scalardl_helm_release_name }} helm/helm-charts/charts/scalardl
    --namespace {{ kubernetes_namespace }}
    -f {{ remote_directory }}/helm/config/scalardl-custom-values.yaml
  when: deploy_scalardl
