---
- name: Deploy Scalar DL with helm
  kubernetes.core.helm:
    name: "{{ scalardl_helm_release_name }}"
    chart_ref: "{{ helm_charts_repo_name }}/scalardl"
    chart_version: "{{ scalardl_chart_version }}"
    release_namespace: "{{ kubernetes_namespace }}"
    update_repo_cache: yes
    create_namespace: yes
    wait_timeout: "200"
    values_files:
      - "{{ helm_charts_custom_config_path }}/scalardl-custom-values.yaml"
  when: deploy_scalardl | bool
