apiVersion: v2
name: schema-loading
description: Implementation schema loading for scalar-ledger
type: application
version: 1.3.0
appVersion: 1.3.0
deprecated: false
icon: https://scalar-labs.com/wp-content/themes/scalar/assets/img/logo_scalar.svg
keywords:
- scalar-ledger
- DLT
- schema-loading
home: https://scalar-labs.com/
source: ["https://scalardl.readthedocs.io/en/latest/"]
maintainers:
  - name: Paul Dozancuk
    email: paul.dozancuk@scalar-labs.com
  - name: Yusuke Morimoto
    email: yusuke.morimoto@scalar-labs.com
