envoy:
  replicaCount: 3

  prometheusRule:
    enabled: false

  serviceMonitor:
    enabled: false

  grafanaDashboard:
    enabled: false

  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - scalardl-audit
                - key: app.kubernetes.io/app
                  operator: In
                  values:
                    - envoy
            topologyKey: kubernetes.io/hostname
          weight: 50

auditor:
  replicaCount: 3

  scalarAuditorConfiguration:

  auditorProperties: |
    # # Cosmo DB for NoSQL
    # # The Cosmos DB for NoSQL URI
    # scalar.db.contact_points=<COSMOS_DB_FOR_NOSQL_URI>
    #
    # # The Cosmos DB for NoSQL key
    # scalar.db.password=<COSMOS_DB_FOR_NOSQL_KEY>
    #
    # # Cosmos DB for NoSQL storage implementation
    # scalar.db.storage=cosmos

    # # DynamoDB
    # # The AWS region
    # scalar.db.contact_points=<REGION>
    #
    # # The AWS access key ID and secret access key
    # scalar.db.username=<ACCESS_KEY_ID>
    # scalar.db.password=<SECRET_ACCESS_KEY>
    #
    # # DynamoDB storage implementation
    # scalar.db.storage=dynamo

    # # Auditor configurations
    # scalar.dl.auditor.ledger.host=<Host name to access ScalarDL Ledger pods>
    # scalar.dl.auditor.private_key_path=/keys/private-key
    # scalar.dl.auditor.cert_path=/keys/certificate

  extraVolumes:
    - name: auditor-keys
      secret:
        secretName: auditor-keys

  extraVolumeMounts:
    - name: auditor-keys
      mountPath: /keys
      readOnly: true

  prometheusRule:
    enabled: false

  serviceMonitor:
    enabled: false

  grafanaDashboard:
    enabled: false

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - scalardl-audit
                - key: app.kubernetes.io/app
                  operator: In
                  values:
                    - auditor
            topologyKey: kubernetes.io/hostname
          weight: 50

  resources:
    requests:
      cpu: 2000m
      memory: 4Gi
    limits:
      cpu: 2000m
      memory: 4Gi
