replicaCount: 3

scalarDbGraphQlConfiguration:
  #
  # Specify the configuration of a database you use.
  # The following is the example configuration of DynamoDB.
  #
  # contactPoints: <REGION>
  # username: <AWS_ACCESS_KEY_ID>
  # password: <AWS_ACCESS_SECRET_KEY>
  # storage: dynamo

  logLevel: INFO
  path: /graphql
  namespaces: "<comma-separated namespace list>"
  graphiql: "true"

ingress:
  enabled: true
  className: alb
  annotations:
    # ALB
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=60
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /graphql?query=%7B__typename%7D
  hosts:
    - host: ""
      paths:
        - path: /graphql
          pathType: Exact

serviceMonitor:
  enabled: false

prometheusRule:
  enabled: false

grafanaDashboard:
  enabled: false

tolerations:
  - effect: NoSchedule
    key: scalar-labs.com/dedicated-node
    operator: Equal
    value: scalardb

resources:
  requests:
    cpu: 2000m
    memory: 4Gi
  limits:
    cpu: 2000m
    memory: 4Gi

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: scalar-labs.com/dedicated-node
              operator: In
              values:
                - scalardb
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/app
              operator: In
              values:
                - scalardb-graphql
        topologyKey: kubernetes.io/hostname

existingSecret: ""
