apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "schema-loading.fullname" . }}
  labels:
    {{- include "schema-loading.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "schema-loading.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.schemaLoading.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
      - name: schema-import
        image: "{{ .Values.schemaLoading.image.repository }}:{{ .Values.schemaLoading.image.version }}"
        imagePullPolicy: "{{ .Values.schemaLoading.image.pullPolicy }}"
        args:
        - "-h"
        - "{{ .Values.schemaLoading.contactPoints }}"
        - "-P"
        - "{{ .Values.schemaLoading.contactPort }}"
        - "-u"
        - "$(DB_USERNAME)"
        - "-p"
        - "$(DB_PASSWORD)"
        {{- if eq .Values.schemaLoading.database "cassandra" }}
        - "--cassandra"
        - "-n"
        - "NetworkTopologyStrategy"
        - "-R"
        - "{{ .Values.schemaLoading.cassandraReplicationFactor }}"
        {{- else if eq .Values.schemaLoading.database "cosmos" }}
        - "--cosmos"
        - "-r"
        - "{{ .Values.schemaLoading.cosmosBaseResourceUnit }}"
        {{- end }}
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
            {{- if .Values.schemaLoading.existingSecret }}
              name: {{ .Values.schemaLoading.existingSecret }}
            {{- else }}
              name: {{ include "schema-loading.fullname" . }}
            {{- end }}
              key: db-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
            {{- if .Values.schemaLoading.existingSecret }}
              name: {{ .Values.schemaLoading.existingSecret }}
            {{- else }}
              name: {{ include "schema-loading.fullname" . }}
            {{- end }}
              key: db-password
      restartPolicy: Never
  backoffLimit: 0
