base_local_directory: ../conf
kubectl_local_config_directory: "{{ base_local_directory }}/kube_config"
kubectl_version: v1.19.10
kubectl_path: /usr/local/bin/kubectl
kubectl_binary_path: /usr/local/bin/kubectl-{{ kubectl_version }}
kubectl_url: "https://dl.k8s.io/release/{{ kubectl_version }}/bin/linux/amd64/kubectl"
kubectl_checksum_sha256: dbacc1a372f00e2d15ad9a39925191c4e314e39b37dcac3e5b2f5e98f4be0d47
python_package: ['kubernetes', 'openshift', 'kubernetes-validate']
