apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scalardl.fullname" . }}-envoy
  labels:
    {{- include "scalardl-envoy.labels" . | nindent 4 }}
spec:
  minReadySeconds: 0
  replicas: {{ .Values.envoy.replicaCount }}
  selector:
    matchLabels:
      {{- include "scalardl-envoy.selectorLabels" . | nindent 6 }}
  {{- with .Values.envoy.strategy }}
  strategy:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "scalardl-envoy.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.envoy.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.envoy.podSecurityContext | nindent 8 }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      containers:
        - name: {{ .Chart.Name }}-envoy
          securityContext:
            {{- toYaml .Values.envoy.securityContext | nindent 12 }}
          image: "{{ .Values.envoy.image.repository }}:{{ .Values.envoy.image.version }}"
          imagePullPolicy: {{ .Values.envoy.image.pullPolicy }}
          ports:
          - containerPort: 50051
          - containerPort: 50052
          - containerPort: 9001
          env:
          - name: admin_access_log_path
            value: "{{ .Values.envoy.envoyConfiguration.adminAccessLogPath }}"
          - name: scalardl_address
            value: "{{ include "scalardl.fullname" . }}-ledger-headless"
          livenessProbe:
            httpGet:
              path: /ready
              port: 9001
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            {{- toYaml .Values.envoy.resources | nindent 12 }}
      {{- with .Values.envoy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.envoy.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.envoy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
