---
- name: Deploy Scalar Ledger and Envoy in Kubernetes
  hosts: bastion
  gather_facts: no
  become: no
  vars:
    # local_helm_charts_values_directory: "{{ lookup('env','SCALAR_K8S_CONFIG_DIR') }}"
    # docker_registry: "ghcr.io"
    # docker_username: "{{ lookup('env','DOCKER_REGISTRY_USERNAME') }}"
    # docker_password: "{{ lookup('env','DOCKER_REGISTRY_PASSWORD') }}"
    # kubernetes_registry_secret_name: "reg-docker-secrets"
    # kubernetes_namespace: default
    # deploy_scalardl: yes
    # scalardl_helm_release_name: prod
    # scalardl_charts_version: 1.2.2
    # schema_loading_charts_version: 1.3.0
  roles:
    - { role: scalardl, tags: scalardl }
