---
- name: Deploy Prometheus in Kubernetes
  hosts: bastion
  gather_facts: no
  become: no
  vars:
    # namespace: monitoring
    # prometheus_version: 8.14.0
    # deploy_prometheus: true
    # create_dashboard: true
    # alertmanager_notification_activated: false
    # slack_webhook_url: "https://hooks.slack.com/services/xxxxxxxxxxxxxxx/xxxxxxxxxxxxxxx/xxxxxxxxxxxxxxx"
  roles:
    - { role: prometheus, tags: prometheus }
