name: Helm testing and validate for scalar charts
on:
  pull_request:
    branches:
      - master
    paths:
      - "charts/stable/**"
  push:
    branches:
      - master
    paths:
      - "charts/stable/**"
jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Fetch history for chart testing
        run: git fetch --prune --unshallow

      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v1.0.0-rc.2
        with:
          command: lint
          config: .github/ct.yaml

  kubeval-chart:
    runs-on: ubuntu-latest
    needs: lint-chart
    # Uses 1.16.4 since it doesn't support 1.16.13 in https://github.com/instrumenta/kubernetes-json-schema.
    strategy:
      matrix:
        k8s:
          - v1.15.7
          - v1.16.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history for chart testing
        run: git fetch --prune --unshallow

      - name: Run kubeval
        env:
          KUBERNETES_VERSION: ${{ matrix.k8s }}
        run: .github/kubeval.sh

  install-chart:
    name: install-chart
    runs-on: ubuntu-latest
    needs:
      - lint-chart
      - kubeval-chart
    env:
      DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    # Uses 1.16.9 since it doesn't support 1.16.13 in https://hub.docker.com/r/kindest/node/tags.
    strategy:
      matrix:
        k8s:
          - v1.15.11
          - v1.16.9
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history for chart testing
        run: git fetch --prune --unshallow

      - name: Create kind ${{ matrix.k8s }} cluster
        uses: helm/kind-action@v1.0.0-rc.1
        with:
          config: .github/kind-cluster.yaml
          node_image: kindest/node:${{ matrix.k8s }}

      - name: Setup kubernetes (Kind) with registry, cassandra and schema
        run: |
          kubectl cluster-info
          kubectl create secret docker-registry reg-docker-secrets --docker-server=https://index.docker.io/v2/ --docker-username=scalartest --docker-password=${{ env.DOCKER_PASSWORD }}
          kubectl create -f .github/cassandra.yaml
          echo "Wait until cassandra is running" && sleep 100
          kubectl get pods,svc,endpoints,nodes -o wide

      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v1.0.0-rc.2
        with:
          command: "install"
          config: .github/ct.yaml
