default_kubernetes_namespace: logging
monitoring_kubernetes_namespace: monitoring
fluent_manifests_path: /home/{{ ansible_user }}/manifests/fluentbit
fluent_monitor_host: monitor.internal.scalar-labs.com
fluent_monitor_port: 24224
fluent_activate_metrics: yes
fluent_image: fluent/fluent-bit
fluent_tag: 1.3.11
fluent_manifests_files:
  - fluent-bit-configmap.yaml
  - fluent-bit-role-binding.yaml
  - fluent-bit-role.yaml
  - fluent-bit-service-account.yaml
  - fluent-bit-service.yaml
