---
- name: Install Git
  package:
    name: git
    state: present
  register: install_git_result
  until: install_git_result is succeeded
  retries: 3
  delay: 5
  become: yes
  when: helm_plugins | default([]) | length > 0

- name: Install helm plugins
  kubernetes.core.helm_plugin:
    state: present
    plugin_path: "{{ item }}"
    binary_path: "{{ helm_path }}"
  loop: "{{ helm_plugins }}"
  become_user: "{{ ansible_user }}"
